config/routes.rb
Rails.application.routes.draw do
  root 'clients#index'
  resources :orders
  resources :products
  resources :deliverers
  resources :clients

end

app/models/client.rb
# Client class
class Client < ActiveRecord::Base
  has_one :order

  # validates :name,
  #           presence: true,
  #           format: {
  #             with: /\A[a-zA-Z]+\z/,
  #             message: 'only allows letters'
  #           }, length: { in: 2..30 }
  # validates :city,
  #           presence: true,
  #           format: {
  #             with: /\A[a-zA-Z]+\z/,
  #             message: 'only allows letters'
  #           }, length: { in: 2..30 }
  # validates :neighborhood,
  #           presence: true,
  #           length: { in: 2..30 }
  # validates :deliverer_fee,
  #           presence: true,
  #           numericality: { only_integer: true }
  # validates :phone,
  #           presence: true,
  #           uniqueness: true,
  #           length: { in: 4..12 },
  #           numericality: { only_integer: true }
  # validates :order,
  #           allow_blank: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[show edit update destroy block]

  # GET /clients
  # GET localhost:3000/
  # action
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show; end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit; end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.blocked = true
    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: 'Cliente excluido com sucesso' }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(
      :name,
      :city,
      :neighborhood,
      :street,
      :street_number,
      :cep,
      :deliverer_fee,
      :phone,
      :blocked
    )
  end
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
<% if @client.errors.any? %>
<div id="error_explanation" class="alert alert-danger" role="alert">
  <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

  <ul>
    <% @client.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :city %><br>
  <%= f.text_field :city %>
</div>
<div class="field">
  <%= f.label :neighborhood %><br>
  <%= f.text_field :neighborhood %>
</div>
<div class="field">
  <%= f.label :street %><br>
  <%= f.text_field :street %>
</div>
<div class="field">
  <%= f.label :street %><br>
  <%= f.text_field :street %>
</div>
<div class="field">
  <%= f.label :street_number %><br>
  <%= f.text_field :street_number %>
</div>
<div class="field">
  <%= f.label :cep %><br>
  <%= f.text_field :cep %>
</div>
<div class="field">
  <%= f.label :phone %><br>
  <%= f.text_field :phone %>
</div>
<div class="field">
  <%= f.label :deliverer_fee %><br>
  <%= f.text_field :deliverer_fee %>
</div>
<div class="field">
  <%= f.label :blocked %><br>
  <%= f.check_box :blocked %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %>
<%= link_to 'Back', clients_path %>

app/views/clients/index.erb
<p id='notice'><%= notice %></p>

<h1>Listing Clients</h1>

<%= link_to 'New Client', new_client_path %>
<div class='table-responsive'>
  <table id='clients-list' class='table table-hover'>
    <thead>
      <tr>
        <th><%= @clients.model.human_attribute_name('name') %></th>
        <th><%= @clients.model.human_attribute_name('city') %></th>
        <th><%= @clients.model.human_attribute_name('neighborhood') %></th>
        <th><%= @clients.model.human_attribute_name('street') %></th>
        <th><%= @clients.model.human_attribute_name('phone') %></th>
        <th><%= t(:edit) %></th>
        <th><%= t(:destroy) %></th>
        <th><%= @clients.model.human_attribute_name('order') %></th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
      <tr>
        <td data-class-name='priority'><%= client.name %></td>
        <td><%= client.city %></td>
        <td><%= client.neighborhood %></td>
        <td><%= client.street %></td>
        <td><%= client.phone %></td>
        <td><%= link_to (fa_icon 'pencil'), edit_client_path(client), class: "btn btn-sm btn-outline-primary" %></td>
        <td>

        </td>
        <td><%= link_to (fa_icon 'exchange'), new_order_path(client_id: client.id), class: "btn btn-sm btn-outline-primary" %></td>
      </tr>
      <% end %>
      <h1><%= @test %></h1>
    </tbody>
  </table>
</div>

<script>
$(document).ready(function() {
  $('#clients-list').dataTable({
    info: false,
    pageLength: 25,
    lengthChange: false,
    pagingType: 'full_numbers',
    stateSave: true,
    columnDefs: [{
      orderable: false,
      targets: [5, 6, 7, 8]
    }],
    language: {
      paginate: {
        first: '«',
        previous: '‹',
        next: '›',
        last: '»'
      },
      EmptyTable: 'Nenhum registro encontrado',
      LoadingRecords: 'Carregando...',
      Processing: 'Processando...',
      ZeroRecords: 'Nenhum registro encontrado'
    }
  });
});
</script>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @client.neighborhood %>
</p>

<p>
  <strong>street:</strong>
  <%= @client.street %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>


<p>
  <strong>Blocked:</strong>
  <%= @client.blocked %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>