config/routes.rb
Rails.application.routes.draw do
  root 'clients#index'
  resources :orders
  resources :products
  resources :deliverers
  resources :clients

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client
  belongs_to :deliverer
  has_many :ordered_products
  before_save :calc_products_total_quantity
  before_save :calc_order_total_price

  def calc_products_total_quantity
    self.products_total_quantity = 0
    self.ordered_products.each do |ordered|
      self.products_total_quantity += ordered.product_total_quantity
    end
  end

  def calc_order_total_price
    self.order_total_price = 0
    self.ordered_products.each do |ordered|
      self.order_total_price += (ordered.product.unit_price * ordered.product_total_quantity)
    end
  end

  accepts_nested_attributes_for :ordered_products, reject_if: :all_blank, allow_destroy: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :selections, only: [:create, :new, :edit, :update, :show]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new()
    @order.client_id = params[:client_id]
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.client_id = params[:client_id]
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def selections
    @products_selection = Product.all
    @deliverers_selection = Deliverer.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(
        :client_id,
        :deliverer_id,
        :products_total_quantity,
        :order_total_price,
        ordered_products_attributes: %i[id order_id product_id product_total_quantity product_total_price _destroy]
      )
    end
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='col-12'>
      <%= f.label :client_id %>
      <div class='form-control'><%= @order.client.name %></div>
    </div

  <div id='deliverer'  class="pl-4">
    <%= f.label :deliverer_id %>
  </div>
  <div class='field m-1 col-md-3'>
      <%= f.collection_select :deliverer_id, @deliverers_selection, :id, :name, {include_blank: true},class: "form-control" %>
  </div>

  <div>
    <%= link_to_add_association('Adicionar', f, :ordered_products, partial: 'ordered_products_fields' ) %>
  </div>

  <div id='ordered_products'>
    <%= f.fields_for :ordered_products do |ordered_products_fields| %>
      <%= render partial: "ordered_products_fields", locals: { f: ordered_products_fields } %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.button :submit, name: "client_id", value: params[:client_id] %>
  </div>
<% end %>

app/views/orders/_ordered_products_fields.html.erb
<div class='nested-fields'>

  <div class='field row ml-1'>
    <div class='field m-1 col-md-3'>
      <%= f.collection_select :product_id, @products_selection, :id, :name, {include_blank: true},class: "form-control" %>
    </div>
    <div class='field m-1 col-md-3'>
      <%= f.text_field :product_total_quantity, class: "form-control" %>
    </div>

    <div class='field col-md-3 align-self-center'>
      <%= link_to_remove_association('remove',f, class: 'text-light')%>
    </div>
  </div>
  </div>

</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Deliverer</th>
      <th>price</th>
      <th>date</th>
      <th>show</th>
      <th>edit</th>
      <th>delete</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.client.name %></td>
        <td><%= order.deliverer.name %></td>
        <td><%= order.order_total_price %></td>
        <td><%= order.updated_at.strftime("%d/%m/%Y") %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @order.client.name %>
</p>
<p>
  <strong>Deliverer:</strong>
  <%= @order.deliverer.name %>
</p>
<p>
  <table>
    <thead>
      <tr>
        <th>Produto</th>
        <th>Preço</th>
      </tr>
    </thead>
    <tbody>
      <% @order.ordered_products.each do |products|%>
      <tr>
        <th><%= products.product.name %></th>
        <th><%= products.product.unit_price %></th>
        <th><%= products.product_total_quantity %></th>
      </tr>
      <% end %>
    </tbody>
  </table>
</p>
<p>
  <strong> Quantidade Total de Produtos</strong>
  <%= @order.products_total_quantity %>
</p>
<p>
  <strong> Valor Total da Compra </strong>
  <%= @order.order_total_price %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>