config/routes.rb
Rails.application.routes.draw do
  root 'clients#index'
  resources :orders
  resources :products
  resources :deliverers
  resources :clients

end

app/views/layouts/_links.html.erb
<li class="nav-item home">
  <%= link_to clients_path, class: 'nav-link',
    id: 'nav-link-home', data: { turbolinks: false } do %>
    <%= fa_icon 'home', text: 'Início' %>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to deliverers_path, class: 'nav-link',
    id: 'nav-link-order', data: { turbolinks: false } do %>
    <%= fa_icon 'exchange', text: 'Pedidos' %>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to products_path, class: 'nav-link',
    id: 'nav-link-menu', data: { turbolinks: false } do %>
    <%= fa_icon 'list', text: 'Cardápio' %>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to clients_path, class: 'nav-link',
    id: 'nav-link-clients', data: { turbolinks: false } do %>
    <%= fa_icon 'users', text: 'Clientes' %>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to deliverers_path, class: 'nav-link',
    id: 'nav-link-deliverers', data: { turbolinks: false } do %>
    <%= fa_icon 'truck', text: 'Entregadores' %>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to products_path, class: 'nav-link',
    id: 'nav-link-closing-account', data: { turbolinks: false } do %>
    <%= fa_icon 'dollar', text: 'Fechamento' %>
  <% end %>
</li>
<li class="nav-item mt-auto">
  <%= link_to clients_path, class: 'nav-link',
    id: 'nav-link-config', data: { turbolinks: false } do %>
    <%= fa_icon 'cog', text: 'Configurações' %>
  <% end %>
</li>

app/views/layouts/_navbar.html.erb
<nav id='nav_bar' class="navbar navbar-dark bg-primary">
  <%= link_to 'Releazar', clients_path, class: 'navbar-brand p-0 logo',
    id: 'nav-link-home', data: { turbolinks: false } %>
  <form class='form-inline'>
    <input class="form-control d-none d-lg-block"
      type="text" placeholder="Buscar" aria-label="Search">
  </form>

  <div class='nav-section d-lg-none d-xl-none'>
    <div class='nav-toggle'>
      <div class='rectangle-a'></div>
      <div class='rectangle-b'></div>
      <div class='rectangle-c'></div>
    </div>
    <div class='nav-links'>
      <%= render 'layouts/links' %>
    </div>
  </div>
</nav>

<script type='text/javascript'>
$(document).ready(function() {

  let show = true;

  $('.nav-toggle').on('click', function() {
    $('body').toggleClass('hidden', show);
    $('.nav-section').toggleClass('on', show);

    show = !show;
  });
})
</script>

app/views/layouts/_sidebar.html.erb
<nav id='sidebar' class="col-2 d-none d-lg-block sidebar pr-0">
  <div class="sidebar-sticky h-100">
    <ul id='nav' class="nav flex-column h-100">
        <%= render 'layouts/links' %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'/>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <title>Releazar</title>
    <%= favicon_link_tag asset_path('logo.jpg') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='bg-primary'>
    <%= render 'layouts/navbar' %>
    <div class="container-fluid">
      <div class="row">
        <%= render 'layouts/sidebar' %>

        <main id="main" class="col p-3 mr-3 bg-secondary main">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>